name: Deploy ASP.Net Core app to Azure Web App - thamco-customer-web-app

on:
  workflow_run:
    workflows: ["Build ASP.Net Core app - thamco-customer-web-app"]
    types:
      - completed
jobs:
  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'thamco-customer-web-app'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B84610FB9C3944D08DABD7999C241744 }}
